### ISSUE TITLE
Improved Keyboard Bindings

### ISSUE THREAD

**Issue by IgnoredAmbience** [sktw/rainfall-rescue-tools-chrome-extension#1]
Nice extension, thanks! Would you consider including some functionality from a userscript I wrote to improve keybindings for data entry, binding the `Enter` key to tab between fields, or move focus to the Done button as appropriate. (It also makes some style changes that are likely superseded by those already present in the extension).

https://gist.github.com/IgnoredAmbience/800b38847f881d5592e2148fbc3d4bda

**Comment by sktw** [comment]
It would be great to include the improved key bindings - thanks. Is your Zooniverse username IgnoredAmbience (so that I can credit you when I announce the feature)?

**Comment by IgnoredAmbience** [comment]
Yes, same username over there.
